### PR TITLE
PMM-7905 FB for PXC 1.8.0

### PR DESCRIPTION
**Pull request by BupycHuk**

### CODE REVIEW

**Comment by askomorokhov** [comment]
@BupycHuk, please take a look - CI fails.

**Review by jprukner — COMMENTED** [review]
I would suggest to update files in deploy folder, too. when real update is upon us.

**Review by jprukner — APPROVED** [review]

**Comment by jprukner** [comment]
:thinking: CI is still failing, not sure what it is caused by.

**Comment by BupycHuk** [comment]
@askomorokhov @jprukner fixed

**Review by jprukner — APPROVED** [review]

**Review by askomorokhov — APPROVED** [review]

**Pull request merged**
